"""Current-generation Sofar register map (upstream ``plugin_sofar.py``)."""

from .battery import BatteryStrings1To2, BatteryStrings3To8, BatteryTotals
from .battery_pack import BatteryPack
from .device import SofarInverter, identify
from .energy import BatteryEnergy, EnergyTotals
from .enums import (
    BatConfigCellType,
    BatConfigProtocol,
    ChargerUseMode,
    EpsControlMode,
    Fault1,
    Fault2,
    Fault3,
    Fault4,
    Fault5,
    Fault6,
    Fault7,
    Fault8,
    Fault9,
    Fault10,
    Fault11,
    Fault12,
    Fault13,
    Fault14,
    Fault15,
    Fault16,
    Fault17,
    Fault18,
    Fault19,
    Fault22,
    Fault23,
    Fault26,
    Fault27,
    Fault28,
    Fault29,
    Fault30,
    FeedinLimitationMode,
    ParallelMasterslave,
    PassiveModeTimeoutAction,
    PowerControlFlags,
    RemoteSwitchOnOff,
    SyncRtcResult,
    SystemState,
)
from .inverter import GridOutput, Identity, InverterState
from .offgrid import OffGridSinglePhase, OffGridThreePhase, OffGridTotals
from .pv import (
    PvString3,
    PvString4,
    PvStrings1To2,
    PvStrings5To6,
    PvStrings7To8,
    PvStrings9To10,
)
from .rating import InverterRating
from .settings import (
    ActivePowerControl,
    BatteryActiveControl,
    BatteryConfig,
    BatteryConfigId,
    ChargerMode,
    EpsControl,
    FeedInLimit,
    ParallelControl,
    PassiveMode,
    RemoteControl,
    RtcSyncResult,
)

__all__ = [
    "ActivePowerControl",
    "BatConfigCellType",
    "BatConfigProtocol",
    "BatteryActiveControl",
    "BatteryConfig",
    "BatteryConfigId",
    "BatteryEnergy",
    "BatteryPack",
    "BatteryStrings1To2",
    "BatteryStrings3To8",
    "BatteryTotals",
    "ChargerMode",
    "ChargerUseMode",
    "EnergyTotals",
    "EpsControl",
    "EpsControlMode",
    "Fault1",
    "Fault2",
    "Fault3",
    "Fault4",
    "Fault5",
    "Fault6",
    "Fault7",
    "Fault8",
    "Fault9",
    "Fault10",
    "Fault11",
    "Fault12",
    "Fault13",
    "Fault14",
    "Fault15",
    "Fault16",
    "Fault17",
    "Fault18",
    "Fault19",
    "Fault22",
    "Fault23",
    "Fault26",
    "Fault27",
    "Fault28",
    "Fault29",
    "Fault30",
    "FeedInLimit",
    "FeedinLimitationMode",
    "GridOutput",
    "Identity",
    "InverterRating",
    "InverterState",
    "OffGridSinglePhase",
    "OffGridThreePhase",
    "OffGridTotals",
    "ParallelControl",
    "ParallelMasterslave",
    "PassiveMode",
    "PassiveModeTimeoutAction",
    "PowerControlFlags",
    "PvString3",
    "PvString4",
    "PvStrings1To2",
    "PvStrings5To6",
    "PvStrings7To8",
    "PvStrings9To10",
    "RemoteControl",
    "RemoteSwitchOnOff",
    "RtcSyncResult",
    "SofarInverter",
    "SyncRtcResult",
    "SystemState",
    "identify",
]
